### ISSUE TITLE
App beendet sich

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [janexner/FotoTimerAndroid#4]
Wenn ich da drauf klicke, beendet sich die app. ist das so ?

Ich habe die apk von deiner webseite installiert 
(bei fdroid gibts das ja noch nicht, mache ich zu gegebener zeit auch)

Mein Phone:

Samsung S21 5G
Android 14

![photo1716533629](https://github.com/janexner/FotoTimerAndroid/assets/61406324/4760025f-8b94-4e76-9750-06207155b973)

**Comment by janexner** [comment]
Moin! Das wären die Settings... reproduced on fresh Android 14 emulator. Rats! Now fixing...

**Comment by janexner** [comment]
Found it: https://issuetracker.google.com/issues/336842920

**Comment by janexner** [comment]
Should be fixed in 1.0.3, now available on site here: https://www.jan-exner.de/software/android/fototimer

**Comment by mondlicht-und-sterne** [comment]
ist gefixt, danke, man das ging ja fix.
dann mache ich jetzt hier zu.

![photo1716564980](https://github.com/janexner/FotoTimerAndroid/assets/61406324/3cf67afb-390e-4b4e-a943-adb6359b947d)
