### ISSUE TITLE
Theme - use System by default

### ISSUE THREAD

**Issue by licaon-kter** [janexner/FotoTimerAndroid#5]
...and offer Day/Night, Light/Dark as options

**Comment by janexner** [comment]
There is a "Night Mode" in the preferences

**Comment by licaon-kter** [comment]
Do read my Feature Request again :)

**Comment by janexner** [comment]
Are you suggesting a 3-way choice for users? Follow system - always day - always night?

**Comment by licaon-kter** [comment]
Yes, that's the expected pattern. With System by default.

**Comment by janexner** [comment]
Something like this? 
![image](https://github.com/janexner/FotoTimerAndroid/assets/9006232/51d32289-3bf7-419f-96c9-d1a9a326eb34)

**Comment by licaon-kter** [comment]
yup, looks fine :)

**Comment by janexner** [comment]
Q: I have merged the change. Now do I wait for Foto Timer to be available on F-Droid before I open a new issue for an update to this version? Or can I open that issue straight away?

**Comment by licaon-kter** [comment]
you bump versionCode and versionName, add fastlane changelog .txt , tag, build APK from tagged commit, upload APK to github. done

**Comment by janexner** [comment]
No change needed in the yml file? (I think I used a commit rather than a tag)

**Comment by licaon-kter** [comment]
you're on AutoUpdate: https://gitlab.com/fdroid/fdroiddata/-/blob/40723a7b76eef3611d39d890ff744ccc6a88a879/metadata/com.exner.tools.fototimer.yml#L29

The FAQ explains: https://gitlab.com/fdroid/wiki/-/wikis/FAQ#how-long-does-it-take-for-my-app-to-show-up-on-website-and-client

the checkupdate fairy comes soon :wink: https://gitlab.com/users/fdroidci/activity

**Comment by janexner** [comment]
Brill, thank you!
