### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [janexner/FotoTimerAndroid#7]
ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7010684988#L377

will diff soon

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/c11d2b5967c9d13607e93c38e5b31a18b0ba53cf

**Comment by janexner** [comment]
Argh, bugger. Looking into it.

**Comment by janexner** [comment]
Did you launch the build again, and then it worked? https://gitlab.com/fdroid/fdroiddata/-/pipelines/1317370868

**Comment by janexner** [comment]
(or rather the pipeline)

**Comment by licaon-kter** [comment]
that pipeline runs for the added `disable:` line... but it does not build anything that is... disabled :) ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/7011540470

**Comment by licaon-kter** [comment]
[fot11.log](https://github.com/user-attachments/files/15545801/fot11.log)

Looks like https://gitlab.com/fdroid/fdroiddata/-/issues/3138 but we thought we're beyond that

@linsui thoughts?

**Comment by janexner** [comment]
I'll go through those and see.
The diffoscope output tells me about const floats that are marginally different, and recompiling locally did not change that. I did not change any of the build tools on my end, and Meditation Timer went through with the same settings.
Overall, I think I still haven't fully grasped how 'reproducible' is supposed to work...
![image](https://github.com/janexner/FotoTimerAndroid/assets/9006232/3a3b0b4e-d2a1-4445-9f8f-a46f160f21da)

**Comment by licaon-kter** [comment]
Did you clean all the caches before rebuilding locally?

> Overall, I think I still haven't fully grasped how 'reproducible' is supposed to work...

Not sure what "to work" means here :)

The app should be repro, but bugs in tooling... etc

**Comment by janexner** [comment]
OK, that was helpful.

I built on my debian box, ran the inplace-fix.py, and now diffoscope is clean. New apk has been uploaded to my site, which is where the yml points to. I shall also put that on github as the release asset, if I find out how.

Learning: build releases on debian.

**Comment by janexner** [comment]
After a deep clean of Android Studio on Windows, that build also passed the diffoscope test.

**Comment by licaon-kter** [comment]
thanks :tada: https://gitlab.com/fdroid/fdroiddata/-/commit/6228747bfc564951b42284d9fa8f447bbded3c85

**Comment by janexner** [comment]
Well, thank you! And sorry for the mess!

**Comment by licaon-kter** [comment]
Why do you censor the pics? https://tooting.ch/@jexner/112558115657822787 :grimacing:

**Comment by janexner** [comment]
Dunno. I'm not sure if any of those IDs would allow anyone to hack into the system, and they're not necessary, so disappear they must.

**Comment by licaon-kter** [comment]
Everything from F-Droid is public, open, that's the point :)
